dist: trusty
language: python
python:
- '3.6'
sudo: required
addons:
  chrome: stable
cache: pip
env:
  global:
  - DJANGO_111='Django>=1.11,<2.0'
  - DJANGO_DEV='https://github.com/django/django/tarball/master'
  matrix:
  - DJANGO_VERSION=$DJANGO_111
  - DJANGO_VERSION=$DJANGO_DEV
matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO_VERSION=$DJANGO_DEV
before_install:
- export CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
- sudo apt-get install -y openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
- wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
- sudo chown root:root /usr/local/bin/chromedriver
- sudo chmod 0755 /usr/local/bin/chromedriver
install:
- pip install -r callisto_core/requirements/test.txt --upgrade
- pip install $DJANGO_VERSION
script:
- make test
after_success:
- python setup.py tag
notifications:
  slack:
    secure: CVDBtNe8qXyKt6FwZF+kD2SUWvwGZRa3OPeQcRTsQ84vYMRu9Hfd+3EE9NdiNU2tF/+cpJAIn7Ke/SwbpS70Wjr9S547M/kRqxo7EiL35t5gSCYi/B+Z6Wrh90J9mUCMharbEQbxpTfb67jgYmtBCdhDpa0pSnURdd9fCC1kd4Clt6nqIF0+WE4rTM72mMnN/RaywCzpALnbu9ZyU+UZcjd4Ew3mGNqfYq26R4WKWymhyWkoIK1fmJ9yHa5OXEIWgs7QFqHOaDG5APWw9cSmzXE7y1vP38nx3ZwgUDS/Vk7Q/WmHaW27HG2f4Wui289sf8TvNC3MTN/cyS3Pj1NDWpYHKZS5Wu5GfqFxXqDudJk4U26CNte4z4DtLnFJLQnY6py6MP9qqufBHPuoSxpd74Jtv3ssim8bzsedav4JNOnHsG29ckM9TG2BoxW8fcOgWxBgXXiZWxHqJadECcW+tBFznJFoFXGDymXRsv9GqClVdZhmaAzf07H8RPQY58HZQ1udxsTCb2hH8O4UXqqtM/jE+TrfyYldjbR3RL6ozZmC4hggSl9+APyD0h3bQP0fkitv0oaCMapsecZF/Hzy8b4hzXUAqFoDWwDTbbbGOTCM9eMjnBAFd0830crIxIdIfmwBV1fh5dB8PCr8dTTDZ2XNn4OskjVJ3epqewXKElc=
  email: false
deploy:
  on:
    branch: master
  provider: pypi
  user: shipypi
  password:
    secure: "DNAUyNQTlZdtHfb5PTTjGZgu70r09XEbl7C3m8Lx4Mu88oC4WO4yu4dJklhInu75r00Ddgm29CVSQ6Qocjwasog9Madc9bAZrWBhYVlEGAOmGn2+nJMmAnYuWROYlXsPd1dsjdX+Uz1X9SnqhYoU9zcqixq+waPNk6hXGhDsaQURq9VYSxyTvNKey/uKVBj2bW60SP3JAIrGS6+ffRycF/SSILLWkT4KhHePXaQW+hvQDDiMAbzjptPdzpZFQRovdny/1YdkIR9yxWTLYw+tPTLcNLvsHIbpv253HmItGBzAY7dMMc5WGJhXmCx6bG3dhWNCvjATb8vKWAF6Q4TpghX+KfrBqO1mhg1vhjWtZ5/GWmNiBEBDTahl2JSbHRuLrn7CCSBBxa0JDm3VRsXf9Y5S9S3LYQLOqbQVJdkPf3Gy34+t60LJrTRiynZmZBMoNVWoEEUAdjDppx0klEaBNb7qSKBdjfKqFyihSuoAHj7u+xFaWr1lLr/CgpV3oCCGYd/ebnB3OZR7OhpDgchH8IDjeKI/iO+vBT6cGehV2RCXPM4oyR5eP5xSemLrrKiQ1+poN1j5uJHL7F+TAbKuVzAOC/kd9fX5QNqZy6Ua0SRUnIaNnOGug+TGYCiJEeaehZITPgcgdWqjB24d8JTBDaL7vGCPB027z0oX55MUiZk="
